# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_publisher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Publisher'),
        ),
    ]
