# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0002_auto_20160629_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_apk',
            field=models.FileField(blank=True, null=True, upload_to='apk/'),
        ),
        migrations.AddField(
            model_name='application',
            name='app_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='app_mainimage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='app_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
