# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0003_auto_20160629_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='app_subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
