# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:07
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appstore', '0004_auto_20160629_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, null=True)),
                ('category_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('featured_type', models.CharField(choices=[('1', 'HomeScreen_Banner'), ('2', 'HomeScreen_NonBanner'), ('3', 'Category_Banner'), ('4', 'Category_NonBanner')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('1', 'HomeScreen_CategoryRecommendations'), ('2', 'HomeScreen_RecentInstalls'), ('3', 'AppDetail_Recommendations'), ('4', 'Nearby_Recommendations'), ('5', 'SimilarUser_Recommendations')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100, null=True)),
                ('subcategory_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='subcategory_name')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TopFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_rank', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopNewFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_rank', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_rank', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='collection_items',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='app_type',
        ),
        migrations.AddField(
            model_name='application',
            name='states',
            field=models.CharField(choices=[('1', 'Delhi'), ('2', 'Karnataka'), ('3', 'Rajasthan')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='privacy_policy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_subcategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.SubCategory'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='trending',
            name='application',
            field=models.ManyToManyField(to='appstore.Application'),
        ),
        migrations.AddField(
            model_name='trending',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
        migrations.AddField(
            model_name='topnewfree',
            name='application',
            field=models.ManyToManyField(to='appstore.Application'),
        ),
        migrations.AddField(
            model_name='topnewfree',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
        migrations.AddField(
            model_name='topfree',
            name='application',
            field=models.ManyToManyField(to='appstore.Application'),
        ),
        migrations.AddField(
            model_name='topfree',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='application',
            field=models.ManyToManyField(to='appstore.Application'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featured',
            name='application',
            field=models.ManyToManyField(to='appstore.Application'),
        ),
        migrations.AddField(
            model_name='featured',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
    ]
