# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appstore', '0005_auto_20160629_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_apps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='topfree',
            name='app_rank',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='topnewfree',
            name='app_rank',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='trending',
            name='app_rank',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
