# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0006_auto_20160630_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationimage',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
