# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0007_auto_20160701_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='app_mainimage',
        ),
        migrations.AddField(
            model_name='application',
            name='app_icon_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_icon',
            field=models.FileField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
