# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0008_auto_20160701_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationimage',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='applicationimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
