# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0009_auto_20160701_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Publisher'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
    ]
