# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0010_auto_20160701_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
