# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0012_auto_20160702_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='app_features',
        ),
    ]
