# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(null=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='appstore_users', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
