# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0015_auto_20160707_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='featured_type',
            field=models.CharField(choices=[('1', 'HomeScreen_Banner'), ('2', 'App_Banner'), ('3', 'Game_Banner')], max_length=2, null=True),
        ),
    ]
