# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0016_auto_20160707_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_ratingcount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
