# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0017_application_app_ratingcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_apps',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='application',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='application',
            name='app_ratingcount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.RemoveField(
            model_name='topfree',
            name='application',
        ),
        migrations.AddField(
            model_name='topfree',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Application'),
        ),
        migrations.AlterField(
            model_name='topfree',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
        migrations.RemoveField(
            model_name='topnewfree',
            name='application',
        ),
        migrations.AddField(
            model_name='topnewfree',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Application'),
        ),
        migrations.AlterField(
            model_name='topnewfree',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
        migrations.RemoveField(
            model_name='trending',
            name='application',
        ),
        migrations.AddField(
            model_name='trending',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Application'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Category'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
