# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0018_auto_20160709_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='application',
        ),
        migrations.AddField(
            model_name='featured',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Application'),
        ),
        migrations.AlterField(
            model_name='featured',
            name='image',
            field=models.ImageField(null=True, upload_to='featured/'),
        ),
    ]
