# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0020_remove_featured_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='title',
        ),
        migrations.AddField(
            model_name='application',
            name='app_minimum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
