# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0021_auto_20160720_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='app_slug',
        ),
    ]
