# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0022_remove_application_app_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('rowno', models.CharField(choices=[('1', 'row_one'), ('2', 'row_two'), ('3', 'row_three')], max_length=2, null=True)),
                ('applications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Application')),
            ],
        ),
    ]
